if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT)
    message(FATAL_ERROR "INPUT and OUTPUT are required to embed the assembled PICA shader")
endif()
file(READ "${INPUT}" shader HEX)
string(LENGTH "${shader}" hex_length)
if(hex_length LESS 64 OR hex_length GREATER 131072 OR NOT shader MATCHES "^44564c42")
    message(FATAL_ERROR "Expected an assembled DVLB shader, not source or an empty placeholder")
endif()
math(EXPR byte_count "${hex_length}/2")
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," byte_literals "${shader}")
get_filename_component(output_directory "${OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${output_directory}")
file(WRITE "${OUTPUT}" "#pragma once\n#include <array>\n#include <cstdint>\nnamespace starfox::platform::nintendo_3ds {\ninline constexpr std::array<std::uint8_t,${byte_count}> pica_scene_shader{${byte_literals}};\n}\n")
