# Asset-free build-rule coverage. No configure, shader compile or player writes.
cmake_minimum_required(VERSION 3.20)
if(NOT DEFINED SOURCE_DIR)
    message(FATAL_ERROR "SOURCE_DIR is required")
endif()
if(NOT DEFINED RULE_FILE)
    set(RULE_FILE "${SOURCE_DIR}/cmake/DisplayXR.cmake")
endif()
file(READ "${RULE_FILE}" rules)

function(include_closure input visited output)
    if(input IN_LIST visited)
        set(${output} "" PARENT_SCOPE)
        return()
    endif()
    list(APPEND visited "${input}")
    set(closure "${input}")
    file(READ "${input}" contents)
    get_filename_component(directory "${input}" DIRECTORY)
    string(REGEX MATCHALL "(^|\n)[ \t]*#[ \t]*include[ \t]+\"[^\"]+\"" includes "${contents}")
    foreach(include IN LISTS includes)
        string(REGEX REPLACE ".*\"([^\"]+)\".*" "\\1" relative "${include}")
        get_filename_component(child "${directory}/${relative}" REALPATH)
        if(NOT EXISTS "${child}")
            message(FATAL_ERROR "Unresolved quoted shader include: ${child}")
        endif()
        include_closure("${child}" "${visited}" children)
        list(APPEND closure ${children})
    endforeach()
    list(REMOVE_DUPLICATES closure)
    set(${output} "${closure}" PARENT_SCOPE)
endfunction()

# Evaluate the real loop/branch rules, but replace their build-registration
# commands with a collector. Do not configure SDL, download dependencies or
# execute DXC. Source_DIR is used only for read-only include resolution.
function(target_sources)
endfunction()
function(add_custom_command)
    cmake_parse_arguments(rule "VERBATIM" "OUTPUT" "COMMAND;BYPRODUCTS;DEPENDS" ${ARGV})
    get_filename_component(name "${rule_OUTPUT}" NAME)
    if(name MATCHES "^native_reflection_index_[a-z_]+_(dxil|spirv)\\.hpp$")
        set(entry "${source_file}")
    elseif(name MATCHES "^reflected_visibility_[a-z_]+_(dxil|spirv)\\.hpp$")
        set(entry "${index_source}")
    else()
        return()
    endif()
    get_filename_component(entry_absolute "${SOURCE_DIR}/${entry}" REALPATH)
    include_closure("${entry_absolute}" "" required)
    set(actual)
    foreach(dependency IN LISTS rule_DEPENDS)
        get_filename_component(absolute "${SOURCE_DIR}/${dependency}" REALPATH)
        list(APPEND actual "${absolute}")
    endforeach()
    foreach(dependency IN LISTS required)
        if(NOT dependency IN_LIST actual)
            file(RELATIVE_PATH relative "${SOURCE_DIR}" "${dependency}")
            message(FATAL_ERROR "${name} omits consumed include dependency: ${relative}")
        endif()
    endforeach()
    get_property(checked GLOBAL PROPERTY checked_reflection_rules)
    math(EXPR checked "${checked}+1")
    set_property(GLOBAL PROPERTY checked_reflection_rules "${checked}")
    message(STATUS "${name}: complete quoted include closure tracked")
endfunction()

function(evaluate_rules begin end)
    string(FIND "${rules}" "${begin}" first)
    string(FIND "${rules}" "${end}" last)
    if(first LESS 0 OR last LESS_EQUAL first)
        message(FATAL_ERROR "Reflection shader rule anchors changed; update this regression")
    endif()
    math(EXPR size "${last}-${first}")
    string(SUBSTRING "${rules}" ${first} ${size} loop)
    cmake_language(EVAL CODE "${loop}")
endfunction()

set(CMAKE_CURRENT_SOURCE_DIR "${SOURCE_DIR}")
set(CMAKE_CURRENT_BINARY_DIR "${SOURCE_DIR}/unused-dependency-test-output")
set_property(GLOBAL PROPERTY checked_reflection_rules 0)
evaluate_rules("foreach(source_stage IN ITEMS tiles reduce query mapping domains frames optical"
    [=[    target_include_directories(starfox_displayxr PRIVATE "${CMAKE_CURRENT_BINARY_DIR}/generated")]=])
evaluate_rules("foreach(index_stage IN ITEMS tiles reduce query domains optical jets arithmetic)"
    "    foreach(index_check IN ITEMS starfox_reflected_visibility_index_check")
get_property(checked GLOBAL PROPERTY checked_reflection_rules)
if(NOT checked EQUAL 54)
    message(FATAL_ERROR "Expected fifty-four native/diagnostic reflection dependency rules, got ${checked}")
endif()
message(STATUS "All fifty-four reflection DXIL/SPIR-V rules track their complete quoted include closures")
