"""Merge authored EX translations and exact original speaker/text matches."""
import csv
import json
from pathlib import Path
from generate_dialogue_header import literal, source_display_text

ROOT = Path(__file__).resolve().parents[1]
languages = ("ja", "de", "fr", "es")
speakers = {"fox": 0, "rabbit": 1, "falcon": 2, "frog": 3, "pepper": 4, "andross": 5}
original = json.loads((ROOT / "assets/localization/upstream-dialogue.json").read_text(encoding="utf-8"))
lookup = {}
for message in original["messages"]:
    english = message["variants"]["en"]
    speaker = english["speaker"]
    key = (english["text"], speakers[speaker.rstrip('3')] | (128 if speaker.endswith('3') else 0))
    lookup[key] = [source_display_text(message["variants"][lang]["text"])
                   for lang in languages]
with (ROOT / "assets/localization/ex-translations.tsv").open(encoding="utf-8", newline="") as stream:
    authored = {row["id"]: [row[lang] for lang in languages] for row in csv.DictReader(stream, delimiter="\t")}
ex = json.loads((ROOT / "assets/localization/ex-dialogue.json").read_text())
lines = ['// Generated by tools/generate_ex_dialogue_header.py.', '#pragma once',
         '#include <cstdint>', '#include <string_view>', 'namespace starfox::localization {',
         'struct ExDialogue { std::uint32_t address; std::u32string_view values[4]; };',
         'inline constexpr ExDialogue ex_dialogue[] = {']
missing = []
for message in ex["messages"]:
    translated = authored.get(message["id"], lookup.get((message["en"], message["speaker"])))
    if translated is None:
        missing.append(message["id"])
        continue
    lines.append(f'    {{0x{message["address"]:x}, {{' + ', '.join(literal(text) for text in translated) + '}},')
lines += ['};', 'inline std::u32string_view translated_ex_dialogue(std::uint32_t address, unsigned language) {',
          '    if (language == 0 || language > 4) return {};',
          '    for (const auto& row : ex_dialogue) if (row.address == address) return row.values[language - 1];',
          '    return {};', '}', '} // namespace starfox::localization', '']
if missing:
    raise ValueError("Missing EX translations: " + ', '.join(missing))
(ROOT / "include/starfox/localization/ex_dialogue_catalog.hpp").write_text('\n'.join(lines), encoding="ascii")
print(f"EX translated: {len(ex['messages']) - len(missing)}/{len(ex['messages'])}; remaining: {len(missing)}")
