"""Offline native world-effect projection/composition, with include freshness."""
import argparse
import pathlib
import subprocess
import tempfile
from portable_shader_source import source_digest

parser = argparse.ArgumentParser()
parser.add_argument('--dxc')
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
root = pathlib.Path(__file__).resolve().parents[1]
source = root / 'src/render/shaders/calibrated_scene_fx.hlsl'
output = root / 'src/render/shaders/generated/calibrated_scene_fx.hpp'
stamp = '// Source SHA-256: ' + source_digest(source)
stages = (('project', 'cs_6_0', 'scene_fx_project_main'), ('particles', 'cs_6_0', 'scene_fx_project_main'),
          ('fragment', 'ps_6_0', 'scene_fx_fragment_main'))
if args.check:
    if not output.exists():
        raise SystemExit('Native scene FX shaders missing; regenerate with DXC.')
    generated = output.read_text(encoding='utf-8')
    if stamp not in generated.split('\n', 3)[:3] or any(
            f'{stage}_{backend}[]=' not in generated for stage, _, _ in stages for backend in ('spirv', 'dxil')):
        raise SystemExit('Native scene FX shaders stale; regenerate with DXC.')
    raise SystemExit(0)
if not args.dxc:
    parser.error('--dxc required for generation')
text = '// Generated by tools/generate_calibrated_scene_fx.py; do not edit.\n' + stamp
text += '\n#pragma once\nnamespace starfox::render::calibrated_scene_fx_shader {\n'
with tempfile.TemporaryDirectory() as temporary:
    for stage, profile, entry in stages:
        for backend in ('spirv', 'dxil'):
            binary = pathlib.Path(temporary) / f'{stage}.{backend}'
            options = ['-spirv', '-fspv-target-env=vulkan1.0'] if backend == 'spirv' else []
            defines = ['-D', 'STARFOX_SCENE_FX_PROJECT'] if stage != 'fragment' else []
            if stage == 'particles':
                defines += ['-D', 'STARFOX_SCENE_FX_PARTICLES']
            subprocess.run([args.dxc, *options, '-Gis', *defines, '-T', profile,
                            '-E', entry, '-Fo', str(binary), str(source)], check=True)
            if backend == 'dxil':
                text += '#if defined(_WIN32)\n'
            data = binary.read_bytes()
            text += f'inline constexpr unsigned char {stage}_{backend}[]={{\n'
            text += ',\n'.join(','.join(str(b) for b in data[i:i+32]) for i in range(0, len(data), 32)) + '\n};\n'
            if backend == 'dxil':
                text += '#endif\n'
text += '}\n'
with tempfile.NamedTemporaryFile(mode='w', encoding='utf-8', newline='\n', dir=output.parent,
        suffix='.tmp', delete=False) as pending_file:
    pending = pathlib.Path(pending_file.name)
    pending_file.write(text)
try:
    pending.replace(output)
finally:
    pending.unlink(missing_ok=True)
