"""Generate a portable Unicode dialogue lookup without runtime JSON/filesystem use."""
import argparse
import json
from pathlib import Path


def literal(text):
    # Universal escapes avoid compiler execution-charset differences on consoles.
    return 'U"' + ''.join(
        '\\"' if char == '"' else '\\\\' if char == '\\' else
        char if 32 <= ord(char) < 127 else f"\\u{ord(char):04x}"
        for char in text) + '"'


def source_display_text(text):
    # MOJI_0.TRN maps ASCII '#' to the small full-stop glyph. Preserve raw
    # script strings for identity/matching, but never show hashes in Unicode.
    return text.replace("#", ".")


def generate(catalog):
    rows = []
    for message in catalog["messages"]:
        variants = message["variants"]
        source = variants["en"]["text"]
        translations = tuple(source_display_text(variants[lang]["text"])
                             for lang in ("ja", "de", "fr", "es"))
        rows.append("    {" + ', '.join(literal(text) for text in (source, *translations)) + "},")
    return """// Generated by tools/generate_dialogue_header.py. Do not edit.
#pragma once
#include <array>
#include <string_view>
namespace starfox::localization {
struct DialogueTranslation {
    std::u32string_view english, japanese, german, french, spanish;
};
inline constexpr DialogueTranslation original_dialogue[] = {
""" + '\n'.join(rows) + """
};
inline std::u32string_view translated_dialogue(unsigned message_id, unsigned language) {
    if (message_id == 0 || message_id > std::size(original_dialogue)) return {};
    const auto& row = original_dialogue[message_id - 1];
        switch (language) {
        case 1: return row.japanese;
        case 2: return row.german;
        case 3: return row.french;
        case 4: return row.spanish;
        default: return row.english;
        }
}
} // namespace starfox::localization
"""


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("catalog", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    output = generate(json.loads(args.catalog.read_text(encoding="utf-8")))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output, encoding="ascii")
