"""Offline SDL scene shaders, sharing the VR shader's geometry/material logic."""
import argparse
import pathlib
import subprocess
import tempfile
from portable_shader_source import source_digest

parser = argparse.ArgumentParser()
parser.add_argument('--dxc')
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
root = pathlib.Path(__file__).resolve().parents[1]
source = root / 'src/render/shaders/calibrated_scene_portable.hlsl'
connected_source = root / 'src/render/shaders/calibrated_connected_grid.hlsl'
ray_source = root / 'src/render/shaders/calibrated_ray_geometry.hlsl'
composite_source = root / 'src/render/shaders/calibrated_ray_composite.hlsl'
environment_source = root / 'src/render/shaders/calibrated_environment.hlsl'
persistence_source = root / 'src/render/shaders/calibrated_persistence.hlsl'
global_source = root / 'src/render/shaders/calibrated_global.hlsl'
bloom_source = root / 'src/render/shaders/calibrated_bloom.hlsl'
exposure_source = root / 'src/render/shaders/calibrated_exposure.hlsl'
depth_source = root / 'src/render/shaders/calibrated_depth.hlsl'
water_guides_source = root / 'src/render/shaders/calibrated_water_guides.hlsl'
aa_source = root / 'src/render/shaders/calibrated_aa.hlsl'
msaa_source = root / 'src/render/shaders/calibrated_msaa.hlsl'
temporal_aa_source = root / 'src/render/shaders/calibrated_temporal_aa.hlsl'
reflection_history_source = root / 'src/render/shaders/calibrated_reflection_history.hlsl'
output = root / 'src/render/shaders/generated/calibrated_scene_portable.hpp'
stamp = '// Source SHA-256: ' + source_digest(source)
connected_stamp = '// Connected-grid SHA-256: ' + source_digest(connected_source)
ray_stamp = '// Ray-geometry SHA-256: ' + source_digest(ray_source)
composite_stamp = '// Ray-composite SHA-256: ' + source_digest(composite_source)
environment_stamp = '// Environment SHA-256: ' + source_digest(environment_source)
persistence_stamp = '// Persistence SHA-256: ' + source_digest(persistence_source)
global_stamp = '// Global SHA-256: ' + source_digest(global_source)
bloom_stamp = '// Bloom SHA-256: ' + source_digest(bloom_source)
exposure_stamp = '// Exposure SHA-256: ' + source_digest(exposure_source)
depth_stamp = '// Depth SHA-256: ' + source_digest(depth_source)
water_guides_stamp = '// Water-guides SHA-256: ' + source_digest(water_guides_source)
aa_stamp = '// AA SHA-256: ' + source_digest(aa_source)
msaa_stamp = '// MSAA SHA-256: ' + source_digest(msaa_source)
temporal_aa_stamp = '// Temporal-AA SHA-256: ' + source_digest(temporal_aa_source)
reflection_history_stamp = '// Reflection-history SHA-256: ' + source_digest(reflection_history_source)
if args.check:
    if not output.exists():
        raise SystemExit('Calibrated scene shaders stale; regenerate with DXC.')
    # This header is several megabytes. Read/decode once and split only its
    # stamp prefix; repeatedly decoding it and splitting every bytecode line
    # causes unnecessary allocation/IO during memory-constrained builds.
    generated = output.read_text(encoding='utf-8')
    prefix = generated.split('\n', 16)[:16]
    if any(s not in prefix for s in (stamp,connected_stamp,ray_stamp,composite_stamp,environment_stamp,persistence_stamp,global_stamp,bloom_stamp,exposure_stamp,depth_stamp,water_guides_stamp,aa_stamp,msaa_stamp,temporal_aa_stamp,reflection_history_stamp)):
        raise SystemExit('Calibrated scene shaders stale; regenerate with DXC.')
    for stage in ('vertex', 'vertex_motion', 'vertex_motion_msaa', 'vertex_msaa_guides', 'fragment', 'fragment_msaa', 'receiver', 'receiver_msaa', 'surface', 'surface_msaa', 'motion', 'motion_msaa', 'ground_fragment', 'ground_fragment_msaa', 'ground_receiver', 'ground_receiver_msaa', 'ground_surface', 'ground_surface_msaa', 'ground_motion', 'ground_motion_msaa', 'msaa_extract', 'msaa_extract_surface', 'msaa_extract_motion', 'msaa_resolve', 'msaa_resolve_ink', 'depth', 'water_guides', 'water_panel_guides', 'aa_spatial', 'aa_edges', 'aa_weights', 'aa_blend', 'aa_supersample', 'aa_upscale', 'temporal_aa', 'temporal_present', 'reflection_history', 'composite_vertex', 'composite_fragment', 'composite_witness', 'persistence', 'global', 'bloom', 'exposure_meter', 'exposure_reduce', 'exposure_apply', 'connected_project', 'connected_rows', 'ray_geometry', 'environment_pack'):
        for backend in ('spirv', 'dxil'):
            if f'{stage}_{backend}[]=' not in generated:
                raise SystemExit('Calibrated scene shader payload missing.')
    raise SystemExit(0)
if not args.dxc:
    parser.error('--dxc required for generation')
text = '// Generated by tools/generate_calibrated_scene.py; do not edit.\n' + stamp + '\n' + connected_stamp + '\n' + ray_stamp + '\n' + composite_stamp + '\n' + environment_stamp + '\n' + persistence_stamp + '\n' + global_stamp + '\n' + bloom_stamp + '\n' + exposure_stamp
text += '\n' + depth_stamp + '\n' + water_guides_stamp + '\n' + aa_stamp + '\n' + msaa_stamp + '\n' + temporal_aa_stamp + '\n' + reflection_history_stamp + '\n#pragma once\nnamespace starfox::render::calibrated_scene_shader {\n'
with tempfile.TemporaryDirectory() as temporary:
    for emitted_stage, profile in (('vertex', 'vs_6_0'), ('vertex_motion', 'vs_6_0'), ('vertex_motion_msaa', 'vs_6_0'), ('vertex_msaa_guides', 'vs_6_0'), ('fragment', 'ps_6_0'), ('fragment_msaa', 'ps_6_0'), ('receiver', 'ps_6_0'), ('receiver_msaa', 'ps_6_0'), ('surface', 'ps_6_0'), ('surface_msaa', 'ps_6_0'), ('motion', 'ps_6_0'), ('motion_msaa', 'ps_6_0'), ('depth', 'ps_6_0'),
                           ('ground_fragment','ps_6_0'), ('ground_fragment_msaa','ps_6_0'), ('ground_receiver','ps_6_0'), ('ground_receiver_msaa','ps_6_0'),
                           ('ground_surface','ps_6_0'), ('ground_surface_msaa','ps_6_0'), ('ground_motion','ps_6_0'), ('ground_motion_msaa','ps_6_0'),
                           ('msaa_extract','ps_6_0'), ('msaa_extract_surface','ps_6_0'), ('msaa_extract_motion','ps_6_0'), ('msaa_resolve','ps_6_0'), ('msaa_resolve_ink','ps_6_0'), ('reflection_history','cs_6_0'),
                           ('composite_vertex','vs_6_0'), ('composite_fragment','ps_6_0'), ('composite_witness','ps_6_0'), ('water_guides','ps_6_0'), ('water_panel_guides','ps_6_0'), ('persistence','ps_6_0'), ('global','ps_6_0'), ('bloom','ps_6_0'), ('temporal_aa','ps_6_0'), ('temporal_present','ps_6_0'),
                           ('exposure_meter','cs_6_0'), ('exposure_reduce','cs_6_0'), ('exposure_apply','ps_6_0'),
                           ('aa_spatial','ps_6_0'), ('aa_edges','ps_6_0'), ('aa_weights','ps_6_0'), ('aa_blend','ps_6_0'), ('aa_supersample','ps_6_0'), ('aa_upscale','ps_6_0'),
                           ('connected_project', 'cs_6_0'), ('connected_rows', 'cs_6_0'), ('ray_geometry', 'cs_6_0'), ('environment_pack','cs_6_0')):
        for backend in ('spirv', 'dxil'):
            ground = emitted_stage.startswith('ground_')
            stage = emitted_stage.removeprefix('ground_') if ground else emitted_stage
            panel_water = stage == 'water_panel_guides'
            if panel_water:
                stage = 'water_guides'
            binary = pathlib.Path(temporary) / (emitted_stage + '.' + backend)
            options = ['-spirv', '-fspv-target-env=vulkan1.0'] if backend == 'spirv' else []
            if backend == 'spirv' and stage in ('surface','surface_msaa','motion','motion_msaa'):
                # HLSL SV_Position.w is clip W; Vulkan's raw FragCoord.w is
                # reciprocal W. Normalize only this native depth-guide entry.
                options += ['-fvk-use-dx-position-w']
            compute = profile.startswith('cs_')
            composite = stage.startswith(('composite_', 'aa_', 'temporal_')) or stage in ('persistence','global','bloom','depth','water_guides')
            defines = [] if compute or composite else ['-D', 'STARFOX_SDL_SCENE_' + ('FRAGMENT' if stage in ('receiver','surface','motion') else stage.upper())]
            if panel_water:
                defines = ['-D', 'STARFOX_WATER_PANEL_GUIDES']
            entry = 'fragment_'+stage+'_main' if stage in ('receiver','surface','motion') else stage+'_fragment_main' if stage.startswith(('aa_', 'temporal_')) or stage in ('persistence','global','bloom','depth','water_guides') else stage + ('_main' if compute or composite else '_textured_main')
            if stage=='fragment_msaa':
                defines=['-D','STARFOX_SDL_SCENE_FRAGMENT','-D','STARFOX_CALIBRATED_MSAA']
                entry='fragment_textured_main'
            if stage=='composite_witness':
                defines=['-D','STARFOX_CALIBRATED_EDGE_WITNESS']
            if stage=='vertex_msaa_guides':
                defines=['-D','STARFOX_SDL_SCENE_VERTEX','-D','STARFOX_CALIBRATED_MSAA_GUIDES']
                entry='vertex_textured_main'
            if stage in ('vertex_motion','vertex_motion_msaa'):
                defines=['-D','STARFOX_SDL_SCENE_VERTEX']
                if stage=='vertex_motion_msaa': defines+=['-D','STARFOX_CALIBRATED_MSAA_GUIDES']
                entry='vertex_motion_main'
            if stage in ('receiver_msaa','surface_msaa','motion_msaa'):
                defines=['-D','STARFOX_SDL_SCENE_FRAGMENT','-D','STARFOX_CALIBRATED_MSAA','-D','STARFOX_CALIBRATED_MSAA_GUIDES']
                entry='fragment_'+stage+'_main'
            if stage.startswith('msaa_'):
                defines=['-D','STARFOX_MSAA_EXTRACT'] if stage.startswith('msaa_extract') else []
                if stage=='msaa_resolve_ink': defines=['-D','STARFOX_MSAA_NATIVE_INK']
                entry='msaa_resolve_fragment_main' if stage=='msaa_resolve_ink' else stage+'_fragment_main'
            if stage.startswith('exposure_'):
                defines = ['-D', 'STARFOX_' + stage.upper()]
                entry = stage + ('_fragment_main' if stage=='exposure_apply' else '_main')
            if ground:
                defines += ['-D', 'STARFOX_CALIBRATED_GROUND_SURFACE']
            # Match the existing upstream SMAA compute build: DXC's -Gis
            # leaves opaque texture parameter stores in this graphics adapter
            # and produces invalid Vulkan SPIR-V. Other native stages stay strict.
            strict = [] if stage.startswith('aa_') else ['-Gis']
            subprocess.run([args.dxc, *options, *strict, *defines,
                            '-T', profile, '-E', entry, '-Fo', str(binary),
                            str(reflection_history_source if stage=='reflection_history' else water_guides_source if stage=='water_guides' else temporal_aa_source if stage.startswith('temporal_') else msaa_source if stage.startswith('msaa_') else aa_source if stage.startswith('aa_') else depth_source if stage=='depth' else exposure_source if stage.startswith('exposure_') else bloom_source if stage=='bloom' else global_source if stage=='global' else persistence_source if stage=='persistence' else composite_source if composite else environment_source if stage=='environment_pack' else ray_source if stage=='ray_geometry' else connected_source if compute else source)], check=True)
            if backend == 'dxil':
                text += '#if defined(_WIN32)\n'
            data = binary.read_bytes()
            text += 'inline constexpr unsigned char ' + emitted_stage + '_' + backend + '[]={\n'
            text += ',\n'.join(','.join(str(b) for b in data[i:i+32])
                              for i in range(0, len(data), 32)) + '\n};\n'
            if backend == 'dxil':
                text += '#endif\n'
text += '}\n'
# Publish complete compiler output; do not expose a partly written header.
with tempfile.NamedTemporaryFile(mode='w', encoding='utf-8', newline='\n',
        dir=output.parent, suffix='.tmp', delete=False) as generated:
    pending = pathlib.Path(generated.name)
    generated.write(text)
try:
    pending.replace(output)
finally:
    pending.unlink(missing_ok=True)
