"""Compile ScaleFX passes and texture preparation for Vulkan, Metal and D3D12."""
import argparse
import hashlib
import pathlib
import re
import subprocess
import tempfile

parser = argparse.ArgumentParser()
parser.add_argument('--dxc')
parser.add_argument('--spirv-cross')
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
root = pathlib.Path(__file__).resolve().parents[1]
source = root / 'src/render/shaders/scalefx_portable.hlsl'
destination = root / 'src/render/shaders/generated/scalefx_portable.hpp'
stamp = '// Source SHA-256: ' + hashlib.sha256(
    source.read_bytes().replace(b'\r\n', b'\n')).hexdigest()
if args.check:
    if not destination.exists() or stamp not in destination.read_text().splitlines()[:3] or any(
            f'unsigned char dxil{i}[]=' not in destination.read_text() for i in range(6)):
        raise SystemExit('ScaleFX shaders are stale.')
    if any(destination.read_text().count(guard)!=6 for guard in ('#if defined(_WIN32)', '#if defined(__APPLE__)')):
        raise SystemExit('ScaleFX platform payload guards are stale.')
    raise SystemExit(0)
if not args.dxc or not args.spirv_cross:
    parser.error('--dxc and --spirv-cross required')
output = ['// Generated by tools/generate_scalefx.py; do not edit.', stamp,
          '#pragma once', 'namespace starfox::render::scalefx_shader {']
with tempfile.TemporaryDirectory() as temporary:
    for index in range(6):
        spv = pathlib.Path(temporary) / f'pass{index}.spv'
        msl = pathlib.Path(temporary) / f'pass{index}.msl'
        dxil = pathlib.Path(temporary) / f'pass{index}.dxil'
        subprocess.run([args.dxc, '-spirv', '-fspv-target-env=vulkan1.0',
                        '-T', 'cs_6_0', '-E', 'main', '-Wno-logical-op-parentheses',
                        '-D', f'SCALEFX_PASS={index}', '-Fo', str(spv), str(source)], check=True)
        subprocess.run([args.spirv_cross, str(spv), '--msl', '--msl-version',
                        '20100', '--output', str(msl)], check=True)
        subprocess.run([args.dxc, '-T', 'cs_6_0', '-E', 'main', '-Wno-logical-op-parentheses',
                        '-D', f'SCALEFX_PASS={index}', '-Fo', str(dxil), str(source)], check=True)
        metal = msl.read_text()
        # SDL compute buffer slots: uniforms, read-only buffers, writable buffer.
        # Optimized-out inputs need no Metal binding; their remaining slots
        # still retain the same indices across every pass.
        for name, slot in {'Settings': 0, 'sourceData': 1, 'metricData': 2,
                           'originalData': 3, 'outputData': 1 if index == 5 else 4}.items():
            metal, count = re.subn(r'(\b' + name + r'\s*\[\[buffer\()\d+(\)\]\])',
                                  lambda m: m[1] + str(slot) + m[2], metal)
            if count > 1 or (name in ('Settings', 'outputData') and count != 1):
                raise RuntimeError(f'Unexpected Metal binding: {name}, pass {index}')
        blob = spv.read_bytes()
        output.append(f'inline constexpr unsigned char spirv{index}[]={{')
        output.extend(','.join(str(b) for b in blob[i:i+32]) + ','
                      for i in range(0, len(blob), 32))
        output.append('};')
        native_blob = dxil.read_bytes()
        output.append('#if defined(_WIN32)')
        output.append(f'inline constexpr unsigned char dxil{index}[]={{')
        output.extend(','.join(str(b) for b in native_blob[i:i+32]) + ','
                      for i in range(0,len(native_blob),32))
        output.append('};')
        output.extend(['#endif', '#if defined(__APPLE__)'])
        output.append(f'inline constexpr char metal{index}[]=R"SFXMETAL(\n'
                      + metal + ')SFXMETAL";')
        output.append('#endif')
output.append('}')
destination.write_text('\n'.join(output) + '\n', encoding='utf-8', newline='\n')
