"""Offline Vulkan graphics shaders; no compiler needed by the shipped game."""
import argparse
import errno
import os
import pathlib
import struct
import subprocess
import tempfile
import time
from portable_shader_source import source_digest

parser = argparse.ArgumentParser()
parser.add_argument('--dxc')
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
root = pathlib.Path(__file__).resolve().parents[1]
source = root / 'src/vr/shaders/scene.hlsl'
output = root / 'src/vr/shaders/scene_spirv.hpp'
stamp = '// Source SHA-256: ' + source_digest(source)
if args.check:
    if not output.exists() or stamp not in output.read_text().splitlines()[:3]:
        raise SystemExit('VR shaders stale; regenerate with DXC.')
    raise SystemExit(0)
if not args.dxc:
    parser.error('--dxc required for generation')
text = '// Generated by tools/generate_vr_shaders.py; do not edit.\n' + stamp + '\n#pragma once\n#include <cstdint>\nnamespace starfox::vr::shader {\n'
with tempfile.TemporaryDirectory() as temporary:
    for stage, profile in [('vertex', 'vs_6_0'), ('vertex_textured', 'vs_6_0'), ('fragment', 'ps_6_0'), ('fragment_textured', 'ps_6_0'), ('connected_project', 'cs_6_0'), ('connected_rows', 'cs_6_0')]:
        binary = pathlib.Path(temporary) / (stage + '.spv')
        subprocess.run([args.dxc, '-spirv', '-fspv-target-env=vulkan1.0', '-T', profile,
                        '-E', stage + '_main', '-Fo', str(binary), str(source)], check=True)
        blob = binary.read_bytes()
        words = struct.unpack('<' + 'I' * (len(blob) // 4), blob)
        text += 'inline constexpr std::uint32_t ' + stage + '[]={\n'
        text += ',\n'.join(','.join(hex(v) for v in words[i:i+8]) for i in range(0, len(words), 8)) + '\n};\n'
text += '}\n'
# Never truncate a valid generated header while Windows has it open for a
# compiler/scanner. Publish the complete result atomically, with a bounded
# retry for transient sharing failures; persistent failures still stop builds.
with tempfile.NamedTemporaryFile(mode='w', encoding='utf-8', newline='\n',
        dir=output.parent, prefix=output.stem + '.', suffix='.tmp', delete=False) as generated:
    pending = pathlib.Path(generated.name)
    generated.write(text)
try:
    for attempt in range(6):
        try:
            pending.replace(output)
            break
        except OSError as error:
            if os.name != 'nt' or error.errno not in (errno.EACCES, errno.EBUSY, errno.EINVAL, errno.EPERM) or attempt == 5:
                raise
            time.sleep(.1 * (attempt + 1))
finally:
    pending.unlink(missing_ok=True)
