"""Compile menu translations into Unicode literals."""
import csv
from pathlib import Path
from generate_dialogue_header import literal

root = Path(__file__).resolve().parents[1]
with (root / "assets/localization/menu.tsv").open(encoding="utf-8", newline="") as stream:
    rows = list(csv.reader(stream, delimiter="\t"))[1:]
output = ['// Generated by tools/generate_menu_header.py.', '#pragma once',
          '#include <string_view>', 'namespace starfox::localization {',
          'struct MenuText { std::string_view key; std::u32string_view values[4]; };',
          'inline constexpr MenuText menu_text[] = {']
for row in rows:
    output.append('    {"' + row[0] + '", {' + ', '.join(literal(value) for value in row[1:]) + '}},')
output += ['};', 'inline std::u32string_view menu_translation(std::string_view text, unsigned language) {',
           '    if (language == 0 || language > 4) return {};',
           '    for (const auto& row : menu_text) if (row.key == text) return row.values[language - 1];',
           '    return {};', '}', '} // namespace starfox::localization', '']
(root / "include/starfox/localization/menu_catalog.hpp").write_text('\n'.join(output), encoding="ascii")
