#!/usr/bin/env python3
"""Compile the newly authored C materials/rear solids; no cartridge mesh."""
import argparse
import json
from pathlib import Path
root = Path(__file__).resolve().parents[1]
assets = root / 'assets/vr/cockpit-c'
materials = json.loads((assets / 'materials.json').read_text())['materials']
geometry = json.loads((assets / 'geometry.json').read_text())
assignments = json.loads((assets / 'source-face-materials.json').read_text())['assignments']
def rgb(name):
    r, g, b = materials[name]
    return f'0x{r:02x}{g:02x}{b:02x}U'
def number(v):
    return f'{float(v):.9f}F'
lines = ['// Generated by tools/generate_cockpit_assets.py. New assets only; no cartridge mesh.',
         'namespace starfox::vr::cockpit_assets {',
         'struct FrontMaterial {unsigned face, triangle, first; uint32_t rgb;};',
         'inline constexpr FrontMaterial front[]{']
for a in assignments:
    lines.append(f'    {{{a["source_face"]},{a["triangle_within_face_range"]},{a["first_vertex"]},{rgb(a["material"])}}},')
lines += ['};', 'struct RearTriangle {std::array<std::array<float,3>,3> points; uint32_t rgb;};',
          'inline constexpr RearTriangle rear[]{']
for module in geometry['modules']:
    lines.append('// ' + module['name'])
    for triangle, material in zip(module['triangle_indices'], module['triangle_materials'], strict=True):
        points = [[v+p for v,p in zip(module['vertices_local_m'][i], module['pivot_pilot_local_m'], strict=True)] for i in triangle]
        lines.append('    {{{{' + '},{'.join(','.join(number(v) for v in p) for p in points) + '}}},' + rgb(material) + '},')
lines += ['};', '}']
text = '\n'.join(lines) + '\n'
output = root / 'src/vr/cockpit_assets.inc'
parser = argparse.ArgumentParser(); parser.add_argument('--check', action='store_true'); args = parser.parse_args()
if args.check:
    if output.read_text() != text: raise SystemExit('Cockpit assets are stale; run tools/generate_cockpit_assets.py')
else: output.write_text(text)
