"""Offline Vulkan/Metal shader generation. Requires SPIR-V-enabled DXC and SPIRV-Cross.

Validated tool versions: DXC v1.9.2607; SPIRV-Cross be71ee8c12cd7dc5ca8fa9581f708c2e8561fe2a.
No shader compiler is downloaded or invoked by the shipped game.
"""
import argparse
import hashlib
import pathlib
import re
import subprocess
import tempfile

parser = argparse.ArgumentParser()
parser.add_argument('--dxc')
parser.add_argument('--spirv-cross')
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
root = pathlib.Path(__file__).resolve().parents[1]
destination = root / 'src/render/shaders/generated'
destination.mkdir(exist_ok=True)
sources = ['effects_compute.hlsl', 'xbrz_compute.hlsli', 'xbrz_weights.hlsli', 'edge_corners.hlsli', 'environment_material.hlsli', 'backdrop_sample.hlsli', '../../../include/starfox/render/ex_face_planet_regions.inc', '../../../include/starfox/render/ex_city_moons.inc', '../../../include/starfox/render/lava_surface.inc']
sources.append('../../../include/starfox/render/special_fx.inc')
sources.append('../../../include/starfox/render/global_enhancements.inc')
sources.append('../../../include/starfox/render/scene_enhancements.inc')
sources.append('../../../include/starfox/render/depth_enhancements.inc')
sources.append('../../../include/starfox/render/ambient_occlusion.inc')
fingerprint = hashlib.sha256(b''.join((root / 'src/render/shaders' / name).read_bytes().replace(b'\r\n', b'\n')
                                     for name in sources)).hexdigest()
stamp = '// Source SHA-256: ' + fingerprint
if args.check:
    for xbrz in (0, 1):
        generated = (destination / f'effects_portable_{xbrz}.hpp').read_text()
        if (stamp not in generated.splitlines()[:3] or 'unsigned char dxil[]=' not in generated
                or '#if defined(_WIN32)' not in generated or '#if defined(__APPLE__)' not in generated):
            raise SystemExit('Portable effects are stale; regenerate with DXC and SPIRV-Cross.')
    raise SystemExit(0)
if not args.dxc or not args.spirv_cross:
    parser.error('--dxc and --spirv-cross are required unless --check is specified')
for xbrz in (0, 1):
    with tempfile.TemporaryDirectory() as temp:
        spv = pathlib.Path(temp) / 'effects.spv'
        dxil = pathlib.Path(temp) / 'effects.dxil'
        msl = pathlib.Path(temp) / 'effects.msl'
        subprocess.run([args.dxc, '-spirv', '-fspv-target-env=vulkan1.0', '-T', 'cs_6_0', '-E', 'main',
                        '-D', f'STARFOX_ENABLE_XBRZ={xbrz}', '-D', 'STARFOX_SDL_GPU=1', '-Fo', str(spv),
                        str(root / 'src/render/shaders/effects_compute.hlsl')], check=True)
        subprocess.run([args.spirv_cross, str(spv), '--msl', '--msl-version', '20100', '--output', str(msl)], check=True)
        subprocess.run([args.dxc, '-T', 'cs_6_0', '-E', 'main',
                        '-D', f'STARFOX_ENABLE_XBRZ={xbrz}', '-D', 'STARFOX_SDL_GPU=1',
                        '-Fo', str(dxil), str(root / 'src/render/shaders/effects_compute.hlsl')], check=True)
        metal = msl.read_text()
        # SDL requires uniforms first, followed by read-only storage buffers.
        for name, slot in {'Settings': 0, 'SceneSettings': 1, 'layerTags': 2, 'indexedPixels': 3, 'surfaces': 4, 'shadowMask': 5, 'scalefxPixels': 6, 'setupPixels': 7}.items():
            metal, count = re.subn(r'(\b' + name + r'\s*\[\[buffer\()\d+(\)\]\])',
                                  lambda m: m[1] + str(slot) + m[2], metal)
            if count != 1:
                raise RuntimeError(f'Unexpected Metal binding for {name}: {count}')
        blob = spv.read_bytes()
        rows = [','.join(str(b) for b in blob[i:i+32]) for i in range(0, len(blob), 32)]
        text = '// Generated by tools/generate_portable_effects.py; do not edit.\n' + stamp + '\n#pragma once\n'
        text += 'namespace starfox::render::portable_shader {\ninline constexpr unsigned char spirv[]={\n'
        # Do not ship/parse backend payloads that this platform cannot use.
        # Keep SPIR-V universally available, including optional Vulkan on Apple.
        text += ',\n'.join(rows) + '\n};\n#if defined(_WIN32)\ninline constexpr unsigned char dxil[]={\n'
        native_blob = dxil.read_bytes()
        text += ',\n'.join(','.join(str(b) for b in native_blob[i:i+32]) for i in range(0,len(native_blob),32))
        text += '\n};\n#endif\n#if defined(__APPLE__)\ninline constexpr char metal[]=R"SFXMETAL(\n' + metal + ')SFXMETAL";\n#endif\n}\n'
        (destination / f'effects_portable_{xbrz}.hpp').write_text(text, encoding='utf-8', newline='\n')
