"""Offline compact reflected-incident history; ordinary PSOs stay unchanged."""
import argparse
import pathlib
import subprocess
import tempfile
from portable_shader_source import source_digest

parser = argparse.ArgumentParser()
parser.add_argument('--dxc')
parser.add_argument('--check', action='store_true')
parser.add_argument('--paths', action='store_true', help='Generate full ordered-path history instead of legacy single-hit lobes')
parser.add_argument('--curved', action='store_true', help='Generate the distinct 64-byte liquid/model path consumer')
args = parser.parse_args()
if args.curved and not args.paths:
    parser.error('--curved requires --paths')
root = pathlib.Path(__file__).resolve().parents[1]
stem = 'curved_paths' if args.curved else 'paths' if args.paths else 'lobes'
entry = 'paths' if args.paths else 'lobes'
source = root / f'src/render/shaders/calibrated_reflection_{entry}.hlsl'
output = root / f'src/render/shaders/generated/calibrated_reflection_{stem}.hpp'
stamp = '// Source SHA-256: ' + source_digest(source)
if args.curved:
    stamp += '\n// Curved ABI: 64 bytes; strict IEEE; SPIR-V Vulkan1.2 SignedZeroInfNanPreserve32'
if args.check:
    text = output.read_text(encoding='utf-8') if output.exists() else ''
    if stamp not in text or any(f'{stem}_{backend}[]=' not in text for backend in ('dxil', 'spirv')):
        raise SystemExit('Compact reflection shaders stale; regenerate with DXC.')
    raise SystemExit(0)
if not args.dxc:
    parser.error('--dxc required for generation')
chunks = ['// Generated by tools/generate_reflection_lobes.py; do not edit.\n' + stamp,
          f'\n#pragma once\nnamespace starfox::render::reflection_{stem}_shader {{\n']
with tempfile.TemporaryDirectory() as temporary:
    for backend in ('dxil', 'spirv'):
        payload = pathlib.Path(temporary) / (stem + '.' + backend)
        flags = ['-spirv', '-fspv-target-env=vulkan1.1'] if backend == 'spirv' else []
        if args.curved:
            flags = ['-Gis', '-D', 'STARFOX_DXR_CURVED_PATH_HISTORY=1']
            if backend == 'spirv':
                flags += ['-spirv', '-fspv-target-env=vulkan1.2',
                          '-Oconfig=--simplify-instructions,--eliminate-dead-code-aggressive,--eliminate-dead-functions,--compact-ids']
        optimization = [] if args.curved and backend == 'spirv' else ['-O3']
        subprocess.run([args.dxc, '-T', 'cs_6_0', '-E', f'reflection_{entry}_main', *optimization, '-WX', *flags,
                        '-Fo', str(payload), str(source)], check=True)
        data = payload.read_bytes()
        chunks.append(f'inline constexpr unsigned char {stem}_{backend}[]={{\n')
        for at in range(0, len(data), 16):
            chunks.append(','.join(str(v) for v in data[at:at + 16]) + ',\n')
        chunks.append('};\n')
chunks.append('}\n')
output.write_text(''.join(chunks), encoding='utf-8')
