"""Embed original regional logo tiles/maps and their 2-bpp palette banks."""
from pathlib import Path
import argparse
import hashlib

parser = argparse.ArgumentParser()
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
root = Path(__file__).resolve().parents[1]
data = root / 'upstream-ultrastarfox/SF/DATA'
output = root / 'include/starfox/localization/title_logos.hpp'
lines = ['// Generated by tools/generate_title_logos.py; do not edit.', '#pragma once',
         '#include <array>', '#include <cstdint>', 'namespace starfox::localization {',
         'struct TitleLogo { std::array<std::uint8_t,2048> characters, tilemap; std::array<std::uint16_t,32> palette; };']
for name, art, palette in [('us', 'TI-3-US', 'CP-USP'), ('japan', 'TI-3', 'CP'), ('starwing', 'TI-3-G', 'CP-P')]:
    blobs = [(data / f'{art}.{ext}').read_bytes() for ext in ('CGX', 'SCR')]
    colours = (data / 'COL' / f'{palette}.COL').read_bytes()
    if any(len(blob) != 2048 for blob in blobs) or len(colours) != 1024:
        raise SystemExit('Unexpected source title asset dimensions')
    lines.append('// Source SHA-256: ' + hashlib.sha256(b''.join(blobs) + colours).hexdigest())
    lines.append(f'inline constexpr TitleLogo title_logo_{name}{{')
    for blob in blobs:
        lines.append('{')
        lines.extend(','.join(str(v) for v in blob[i:i+32]) + ',' for i in range(0, len(blob), 32))
        lines.append('},')
    lines.append('{' + ','.join(str(int.from_bytes(colours[i:i+2], 'little')) for i in range(0, 64, 2)) + '}};')
lines.append('} // namespace starfox::localization')
text = '\n'.join(lines) + '\n'
if args.check:
    if not output.exists() or output.read_text() != text:
        raise SystemExit('Regional title assets are stale; run tools/generate_title_logos.py')
else:
    output.write_text(text, encoding='ascii', newline='\n')
