"""Offline FSR1 shader packaging; no compiler is required by the shipped game."""
import argparse
import hashlib
import pathlib
import re
import subprocess
import tempfile
from portable_shader_source import source_digest

p = argparse.ArgumentParser()
p.add_argument('--dxc')
p.add_argument('--spirv-cross')
p.add_argument('--check', action='store_true')
a = p.parse_args()
root = pathlib.Path(__file__).resolve().parents[1]
source = root / 'src/render/shaders/fsr1_portable.hlsl'
headers = [root / 'third_party/fsr1' / n for n in ('ffx_a.h', 'ffx_fsr1.h')]
stamp = '// Source SHA-256: ' + source_digest(source)
destination = root / 'src/render/shaders/generated/fsr1_portable.hpp'
if a.check:
    text = destination.read_text()
    if stamp not in text.splitlines()[:3] or any(
            token not in text for token in ('char spirv[]', 'char dxil[]', 'char metal[]',
                '#if defined(_WIN32)', '#if defined(__APPLE__)')):
        raise SystemExit('FSR1 shaders are stale or incomplete')
    raise SystemExit(0)
if not a.dxc or not a.spirv_cross:
    p.error('--dxc and --spirv-cross required')
with tempfile.TemporaryDirectory() as tmp:
    spv, dxil, msl = [pathlib.Path(tmp) / n for n in ('fsr.spv', 'fsr.dxil', 'fsr.msl')]
    base = [a.dxc, '-HV', '2018', '-T', 'cs_6_0', '-E', 'main']
    subprocess.run([*base, '-Fo', str(dxil), str(source)], check=True)
    subprocess.run([*base, '-spirv', '-fspv-target-env=vulkan1.0', '-Fo', str(spv), str(source)], check=True)
    subprocess.run([a.spirv_cross, str(spv), '--msl', '--msl-version', '20100', '--output', str(msl)], check=True)
    metal = msl.read_text()
    # SDL compute: uniforms at buffer 0, sampled textures before writable ones.
    for name, kind, slot in [('Settings', 'buffer', 0), ('sourceImage', 'texture', 0),
                             ('outputImage', 'texture', 1), ('sourceSampler', 'sampler', 0)]:
        pattern = r'(\b' + name + r'\s*\[\[' + kind + r'\()\d+(\)\]\])'
        metal, count = re.subn(pattern, lambda m: m[1] + str(slot) + m[2], metal)
        if count != 1:
            raise RuntimeError(f'Unexpected Metal binding {name}: {count}')
    def array(name, path):
        data = path.read_bytes()
        rows = [','.join(str(b) for b in data[i:i+32]) for i in range(0, len(data), 32)]
        return 'inline constexpr unsigned char ' + name + '[]={\n' + ',\n'.join(rows) + '\n};\n'
    destination.write_text('// Generated by tools/generate_fsr1.py; do not edit.\n' + stamp
        + '\n#pragma once\nnamespace starfox::render::fsr1_shader {\n'
        + array('spirv', spv) + '#if defined(_WIN32)\n' + array('dxil', dxil) + '#endif\n'
        + '#if defined(__APPLE__)\ninline constexpr char metal[]=R"FSRMETAL(\n' + metal + ')FSRMETAL";\n#endif\n}\n',
        encoding='utf-8', newline='\n')
