"""Compile the resident caster-expansion compute shader for Vulkan."""
import argparse
import pathlib
import struct
import subprocess
import tempfile
from portable_shader_source import source_digest

parser = argparse.ArgumentParser()
parser.add_argument('--dxc')
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
root = pathlib.Path(__file__).resolve().parents[1]
source = root / 'src/vr/shaders/ray_expand.hlsl'
output = root / 'src/vr/shaders/ray_expand_spirv.hpp'
stamp = '// Source SHA-256: ' + source_digest(source)
if args.check:
    if not output.exists() or stamp not in output.read_text().splitlines()[:3]:
        raise SystemExit('VR ray expansion shader is stale')
    raise SystemExit(0)
if not args.dxc:
    parser.error('--dxc is required')
with tempfile.TemporaryDirectory() as temporary:
    binary = pathlib.Path(temporary) / 'ray.spv'
    subprocess.run([args.dxc, '-spirv', '-fspv-target-env=vulkan1.0', '-Gis',
                    '-T', 'cs_6_0', '-E', 'main', '-Fo', str(binary), str(source)], check=True)
    blob = binary.read_bytes()
    words = struct.unpack('<' + 'I' * (len(blob) // 4), blob)
    text = '// Generated by tools/generate_vr_ray_shader.py\n' + stamp
    text += '\n#pragma once\n#include <cstdint>\nnamespace starfox::vr::ray_shader {\n'
    text += 'inline constexpr std::uint32_t spirv[]={\n'
    text += ',\n'.join(','.join(hex(v) for v in words[i:i+8]) for i in range(0, len(words), 8))
    text += '\n};\n}\n'
output.write_text(text, encoding='utf-8', newline='\n')
