"""Restricted syntax adapter for the authoritative shared HLSL colour rules.

This is not a general HLSL translator or a colour-output/performance proof.
"""
from pathlib import Path
import re


def translate_colour(source: str, integer_scalars: bool) -> str:
    vector = "int3" if integer_scalars else "float3"
    source = re.sub(r"\b(light|grey)\.xxx\b", lambda m: f"{vector}({m[1]})", source)
    source = re.sub(r"\bout\s+float4\b", "thread float4&", source)
    source = re.sub(r"\blerp\b", "mix", source)
    # Avoid differing implicit double-literal promotion in the C++ harness;
    # both the HLSL and Metal shader domains are single precision here.
    source = re.sub(r"(?<![\w.])(?:\d+\.\d*|\.\d+)(?:[eE][+-]?\d+)?(?![\w.])",
                    lambda m: m[0] + "f", source)
    if re.search(r"\.xxx\b|\bout\s+|\blerp\b|\b(float[234]x[234]|double|matrix|Texture\w*)\b|#\s*include", source):
        raise ValueError("Unsupported shared colour syntax; update the explicit Metal adapter")
    return source


def material_colour_source(root: Path) -> str:
    calibrated = (root / "src/render/shaders/calibrated_colour.hlsli").read_text(encoding="utf-8")
    scene = (root / "src/vr/shaders/scene_colour.hlsli").read_text(encoding="utf-8")
    return """// Generated by tools/metal_material_colour.py; do not edit.
// Syntax only: equations remain calibrated_colour.hlsli and scene_colour.hlsli.
int dot(int3 a,int3 b) {return a.x*b.x+a.y*b.y+a.z*b.z;}
int3 min(int a,int3 b) {return min(b,int3(a));}
int3 max(int a,int3 b) {return max(b,int3(a));}
#define STARFOX_CALIBRATED_PALETTE
""" + translate_colour(calibrated, True) + "\n" + translate_colour(scene, False)


if __name__ == "__main__":
    root = Path(__file__).resolve().parents[1]
    path = root / "include/starfox/render/metal_material_colour.inc"
    if path.exists():
        raise RuntimeError("Existing generated source; verify before an explicit distinct rewrite")
    path.write_text(material_colour_source(root), encoding="utf-8")
