"""Emit GLSL syntax for the authoritative calibrated HLSL colour equations.

This intentionally supports just these two small colour-only include files,
not arbitrary HLSL. Raster and native rays keep one source of colour recipes.
"""
from pathlib import Path
import re


def translate_colour(source: str, integer_scalars: bool) -> str:
    vectors = {"float3": "vec3", "float4": "vec4", "int3": "ivec3", "uint4": "uvec4"}
    source = re.sub(r"\b(float3|float4|int3|uint4)\b", lambda m: vectors[m[0]], source)
    source = re.sub(r"\blerp\b", "mix", source)
    source = re.sub(r"\boutput\b", "palette_output", source)  # GLSL reserved identifier.
    vector = "ivec3" if integer_scalars else "vec3"
    source = re.sub(r"\b(light|grey)\.xxx\b", lambda m: f"{vector}({m[1]})", source)
    # HLSL brace initializers are GLSL array constructors. Only literal vec3
    # palettes are allowed here, so nested arbitrary initializer syntax fails.
    pattern = r"(const\s+(ivec3|vec3)\s+\w+\[(\d+)\]\s*=)\s*\{([^{}]+)\};"
    source = re.sub(pattern, lambda m: f"{m[1]}{m[2]}[{m[3]}]({m[4]});", source)
    if re.search(r"\.xxx\b|=\s*\{|\b(float[234]|int[234]|uint[234]|lerp)\b", source):
        raise ValueError("Unsupported HLSL colour syntax; update the explicit GLSL adapter")
    return source


def material_colour_source(root: Path) -> str:
    calibrated = (root / "src/render/shaders/calibrated_colour.hlsli").read_text(encoding="utf-8")
    scene = (root / "src/vr/shaders/scene_colour.hlsli").read_text(encoding="utf-8")
    return """// Generated by tools/generate_vulkan_rayquery.py; do not edit.
// Equations come from calibrated_colour.hlsli and scene_colour.hlsli.
int dot(ivec3 a,ivec3 b) {return a.x*b.x+a.y*b.y+a.z*b.z;}
ivec3 min(int a,ivec3 b) {return min(b,a);}
ivec3 max(int a,ivec3 b) {return max(b,a);}
float saturate(float v) {return clamp(v,0.0,1.0);}
vec3 saturate(vec3 v) {return clamp(v,0.0,1.0);}
vec4 saturate(vec4 v) {return clamp(v,0.0,1.0);}
#define STARFOX_CALIBRATED_PALETTE
""" + translate_colour(calibrated, True) + "\n" + translate_colour(scene, False)


def liquid_optics_source(root: Path) -> str:
    """Translate only the shared optical helper, retaining matrix orientation."""
    source = (root / "src/render/shaders/liquid_optics.hlsli").read_text(encoding="utf-8")
    source = source.replace('#include "../../../include/', '#include "../../../../include/')
    source = re.sub(r"\bfloat3x3\b", "mat3", source)
    source = re.sub(r"\bfloat3\b", "vec3", source)
    source = source.replace("(LavaSample)0", "LavaSample(0.,0.,0.,0.,0.,0.)")
    # HLSL mul distinguishes row positions/directions from column normals.
    # rotation is a mathematical matrix, not a GLSL constructor of row vectors.
    source = re.sub(r"\bmul\((hit|direction),rotation\)", r"(\1*rotation)", source)
    source = source.replace("mul(rotation,vec3(dx,-1,dz))", "(rotation*vec3(dx,-1,dz))")
    if re.search(r"\b(float[234](?:x[234])?|mul)\b|\(LavaSample\)0", source):
        raise ValueError("Unsupported HLSL liquid optical syntax; update explicit GLSL adapter")
    return "// Generated from liquid_optics.hlsli; do not edit.\n" + source


def translate_liquid_motion(source: str) -> str:
    """Restricted adapter for the accepted-wave solver, not arbitrary HLSL."""
    source = source.replace('#include "liquid_optics.hlsli"', '#include "vulkan_liquid_optics.glsl"')
    # HLSL constructors take rows; GLSL constructors take columns. Keep both
    # row-vector receiver transport and column-vector normals unchanged.
    for rows in ("old.rotation0.xyz,old.rotation1.xyz,old.rotation2.xyz",
                 "current0.xyz,current1.xyz,current2.xyz"):
        source = source.replace(f"float3x3({rows})", f"transpose(mat3({rows}))")
    source = source.replace("mul(currentHit,transpose(mat3(current0.xyz,current1.xyz,current2.xyz)))",
                            "(currentHit*transpose(mat3(current0.xyz,current1.xyz,current2.xyz)))")
    source = re.sub(r"\b(float[234])\b", lambda m: "vec" + m[1][-1], source)
    source = re.sub(r"\bfloat3x3\b", "mat3", source)
    comparisons = {
        "abs(old.planePoint.xyz)>1.e12": "greaterThan(abs(old.planePoint.xyz),vec3(1.e12))",
        **{f"abs(old.rotation{i})>1.e12": f"greaterThan(abs(old.rotation{i}),vec4(1.e12))" for i in range(3)},
        "old.projection.xy<=0": "lessThanEqual(old.projection.xy,vec2(0))",
        "old.projection.xy>1.e12": "greaterThan(old.projection.xy,vec2(1.e12))",
        "old.extentClip.xy<1": "lessThan(old.extentClip.xy,vec2(1))",
        "old.extentClip.xy>16384": "greaterThan(old.extentClip.xy,vec2(16384))",
        "pixel<0": "lessThan(pixel,vec2(0))",
        "pixel>=old.extentClip.xy": "greaterThanEqual(pixel,old.extentClip.xy)",
        "bary<0": "lessThan(bary,vec2(0))",
    }
    for original, adapted in comparisons.items():
        source = source.replace(f"any({original})", f"any({adapted})")
    source = source.replace("hit=normal=0;", "hit=normal=vec3(0);")
    source = source.replace("error=0;", "error=vec2(0);").replace("seedError=0;", "seedError=vec2(0);")
    source = source.replace("return 0;", "return vec4(0);")
    source = re.sub(r"\b(sample|rsqrt)\b", lambda m: {"sample": "optical", "rsqrt": "inversesqrt"}[m[0]], source)
    source = source.replace("[loop] ", "").replace("[branch] ", "")
    if re.search(r"\b(float[234](?:x[234])?|mul|rsqrt)\b|\[(loop|branch)\]|any\([^)]*[<>]", source):
        raise ValueError("Unsupported HLSL liquid motion syntax; update explicit GLSL adapter")
    return source


def liquid_motion_source(root: Path) -> str:
    source = (root / "src/render/shaders/reflection_liquid_hit_motion.hlsli").read_text(encoding="utf-8")
    return """// Generated from reflection_liquid_hit_motion.hlsli; do not edit.
bool isfinite(float v) {return !isnan(v) && !isinf(v);}
bvec2 isfinite(vec2 v) {return bvec2(isfinite(v.x),isfinite(v.y));}
bvec3 isfinite(vec3 v) {return bvec3(isfinite(v.x),isfinite(v.y),isfinite(v.z));}
bvec4 isfinite(vec4 v) {return bvec4(isfinite(v.x),isfinite(v.y),isfinite(v.z),isfinite(v.w));}
""" + translate_liquid_motion(source)
