# Keep VR artwork resource IDs identical to the shared C++ catalogue.
function(starfox_enhanced_backdrop_resources output_arguments output_files)
    get_filename_component(root "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/.." ABSOLUTE)
    set(catalogue "${root}/include/starfox/render/enhanced_backdrop_library.hpp")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${catalogue}")
    file(STRINGS "${catalogue}" entries REGEX "EnhancedBackdropAsset\\{")
    set(arguments)
    set(files)
    set(identifier 200)
    foreach(entry IN LISTS entries)
        string(REGEX MATCH "\"(assets/enhanced-backdrops/[a-z0-9-]+\\.bmp)\"" matched "${entry}")
        if(NOT matched)
            message(FATAL_ERROR "Invalid enhanced backdrop catalogue entry: ${entry}")
        endif()
        set(path "${root}/${CMAKE_MATCH_1}")
        if(NOT EXISTS "${path}")
            message(FATAL_ERROR "Missing enhanced backdrop: ${path}")
        endif()
        list(APPEND arguments --resource "${identifier}=${path}")
        list(APPEND files "${path}")
        math(EXPR identifier "${identifier}+1")
    endforeach()
    if(NOT files)
        message(FATAL_ERROR "Empty enhanced backdrop catalogue")
    endif()
    set(${output_arguments} "${arguments}" PARENT_SCOPE)
    set(${output_files} "${files}" PARENT_SCOPE)
endfunction()
