# Publish the selected adapter's PCI vendor, never infer it from marketing names.
# Kept separate from ray-tracing interop: FSR1 also works without DXR.
foreach(api IN ITEMS d3d12 vulkan)
    set(backend "${SOURCE_DIR}/src/gpu/${api}/SDL_gpu_${api}.c")
    file(READ "${backend}" code)
    string(FIND "${code}" "starfox.gpu.vendor_id" applied)
    if(applied GREATER_EQUAL 0)
        continue()
    endif()
    if(api STREQUAL "d3d12")
        set(vendor "adapterDesc.VendorId")
    else()
        set(vendor "renderer->physicalDeviceProperties.properties.vendorID")
    endif()
    set(anchor "    // Record device name\n")
    string(FIND "${code}" "${anchor}" found)
    if(found LESS 0)
        message(FATAL_ERROR "Unexpected pinned SDL adapter source: ${backend}")
    endif()
    string(REPLACE "${anchor}" "    SDL_SetNumberProperty(renderer->props, \"starfox.gpu.vendor_id\", ${vendor});\n${anchor}" code "${code}")
    file(WRITE "${backend}" "${code}")
endforeach()
